import { PACKAGE, type ComponentDocEntry } from "../types";

export const ATOM_CORE_DOCS: ComponentDocEntry[] = [
  {
    id: "alert",
    name: "Alert",
    layer: "Atom",
    packageExport: true,
    description: "Mensajes de estado con icono SVG, título opcional y cierre dismissible.",
    importLine: `import { Alert } from "${PACKAGE}";`,
    usage: `<Alert type="success" title="Listo">Cambios guardados.</Alert>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Contenido del mensaje." },
      {
        name: "type",
        type: '"info" | "success" | "warning" | "error"',
        default: '"info"',
        description: "Estilo e icono.",
      },
      { name: "title", type: "string", default: "null", description: "Título opcional." },
      {
        name: "dismissible",
        type: "boolean",
        default: "false",
        description: "Muestra botón cerrar.",
      },
      {
        name: "onDismiss",
        type: "() => void",
        default: "null",
        description: "Callback al cerrar.",
      },
      { name: "className", type: "string", default: '""', description: "Clases Tailwind extra." },
    ],
  },
  {
    id: "badge",
    name: "Badge",
    layer: "Atom",
    packageExport: true,
    description: "Chip o etiqueta compacta con variantes cyan/purple y tamaños.",
    importLine: `import { Badge } from "${PACKAGE}";`,
    usage: `<Badge variant="success" size="sm" icon={<IconCheck />}>Activo</Badge>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Texto del badge." },
      {
        name: "variant",
        type: '"cyan" | "purple" | "success" | "highlight"',
        default: '"cyan"',
        description: "Paleta.",
      },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Tamaño." },
      {
        name: "icon",
        type: "ReactNode",
        default: "null",
        description: "Icono SVG opcional a la izquierda.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "button",
    name: "Button",
    layer: "Atom",
    packageExport: true,
    description: "Botón con variantes del design system y anillo focus-visible para teclado.",
    importLine: `import { Button } from "${PACKAGE}";`,
    usage: `<Button variant="primary" size="md" onClick={handleSave}>Guardar</Button>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Etiqueta del botón." },
      {
        name: "variant",
        type: '"primary" | "secondary" | "outline" | "ghost"',
        default: '"primary"',
        description: "Estilo visual.",
      },
      {
        name: "size",
        type: '"sm" | "md" | "lg"',
        default: '"md"',
        description: "Padding y tipografía.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "divider",
    name: "Divider",
    layer: "Atom",
    packageExport: true,
    description: "Separador horizontal o vertical con etiqueta central opcional.",
    importLine: `import { Divider } from "${PACKAGE}";`,
    usage: `<Divider label="o continúa" variant="cyan" size="md" />`,
    props: [
      {
        name: "variant",
        type: '"default" | "cyan" | "purple" | "dotted" | "gradient"',
        default: '"default"',
        description: "Estilo de línea.",
      },
      {
        name: "orientation",
        type: '"horizontal" | "vertical"',
        default: '"horizontal"',
        description: "Dirección.",
      },
      {
        name: "label",
        type: "string",
        default: "null",
        description: "Texto entre líneas (solo horizontal).",
      },
      {
        name: "size",
        type: '"sm" | "md" | "lg"',
        default: '"md"',
        description: "Margen vertical.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "gradient-text",
    name: "GradientText",
    layer: "Atom",
    packageExport: true,
    description: "Texto con degradado cyan–purple (u otras variantes).",
    importLine: `import { GradientText } from "${PACKAGE}";`,
    usage: `<GradientText as="h1" variant="cyan-purple">Título</GradientText>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Contenido." },
      {
        name: "variant",
        type: "string",
        default: '"cyan-purple"',
        description: "cyan-purple, purple-cyan, cyan-only, purple-only, blue-cyan.",
      },
      {
        name: "as",
        type: "string",
        default: '"span"',
        description: "Elemento HTML (span, h1, p…).",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "input",
    name: "Input",
    layer: "Atom",
    packageExport: true,
    description: "Campo de texto con label, icono, error y estilos focus-visible.",
    importLine: `import { Input } from "${PACKAGE}";`,
    usage: `<Input label="Email" variant="default" placeholder="tu@email.com" />`,
    props: [
      {
        name: "placeholder",
        type: "string",
        default: '"Enter text..."',
        description: "Placeholder.",
      },
      {
        name: "variant",
        type: '"default" | "purple" | "minimal"',
        default: '"default"',
        description: "Estilo del campo.",
      },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', description: "Tamaño." },
      { name: "label", type: "string", default: "null", description: "Etiqueta superior." },
      {
        name: "icon",
        type: "ReactNode",
        default: "null",
        description: "Icono SVG a la izquierda.",
      },
      {
        name: "error",
        type: "string",
        default: "null",
        description: "Mensaje de error bajo el campo.",
      },
      { name: "disabled", type: "boolean", default: "false", description: "Estado deshabilitado." },
      { name: "className", type: "string", default: '""', description: "Clases en el input." },
      {
        name: "...props",
        type: "input attrs",
        default: "—",
        description: "Resto de atributos nativos (value, onChange, type…).",
      },
    ],
  },
];
