import { PACKAGE, type ComponentDocEntry } from "../types";

export const ATOM_NAV_DOCS: ComponentDocEntry[] = [
  {
    id: "link",
    name: "Link",
    layer: "Atom",
    packageExport: true,
    description: "Enlace con scroll suave a anclas (#id) y variantes de color.",
    importLine: `import { Link } from "${PACKAGE}";`,
    usage: `<Link href="#seccion" variant="default">Ir a sección</Link>`,
    props: [
      { name: "href", type: "string", default: "—", description: "URL o ancla." },
      { name: "children", type: "ReactNode", default: "—", description: "Texto del enlace." },
      { name: "target", type: "string", default: '"_self"', description: "Target del anchor." },
      {
        name: "variant",
        type: '"default" | "purple" | "accent"',
        default: '"default"',
        description: "Color y focus ring.",
      },
      { name: "className", type: "string", default: "—", description: "Clases extra." },
    ],
  },
  {
    id: "dynamic-link",
    name: "DynamicLink",
    layer: "Atom",
    packageExport: true,
    description: "NavLink de react-router-dom con estado visitado y activo.",
    importLine: `import { DynamicLink } from "${PACKAGE}";`,
    usage: `<DynamicLink to="/docs">Documentación</DynamicLink>`,
    props: [
      { name: "to", type: "string", default: "—", description: "Ruta de React Router." },
      { name: "children", type: "ReactNode", default: "—", description: "Texto del enlace." },
      {
        name: "className",
        type: "string",
        default: '""',
        description: "Clases extra en el NavLink.",
      },
    ],
    notes: [
      "Requiere BrowserRouter (o equivalente) en el árbol de la app consumidora.",
      "En el playground, enlaza a rutas como /docs/button para ver estado activo.",
    ],
  },
  {
    id: "image",
    name: "Image",
    layer: "Atom",
    packageExport: true,
    description: "Imagen con dimensiones y alt por defecto igual al ancho si height es 0.",
    importLine: `import { Image } from "${PACKAGE}";`,
    usage: `<Image source="/logo.png" alternateText="Logo" width={120} />`,
    props: [
      { name: "source", type: "string", default: "—", description: "src de la imagen." },
      { name: "alternateText", type: "string", default: "—", description: "Texto alternativo." },
      { name: "width", type: "number", default: "100", description: "Ancho en px." },
      { name: "height", type: "number", default: "0", description: "Alto; 0 usa width como alto." },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "line",
    name: "Line",
    layer: "Atom",
    packageExport: true,
    description: "Línea horizontal simple (hr) con variantes de borde.",
    importLine: `import { Line } from "${PACKAGE}";`,
    usage: `<Line variant="cyan" className="my-8" />`,
    props: [
      {
        name: "variant",
        type: '"default" | "cyan" | "purple" | "subtle"',
        default: '"default"',
        description: "Color del borde.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "note",
    name: "Note",
    layer: "Atom",
    packageExport: true,
    description: "Párrafo secundario en gris para notas al pie o aclaraciones.",
    importLine: `import { Note } from "${PACKAGE}";`,
    usage: `<Note id="nota-1">Requiere Tailwind en el proyecto.</Note>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Contenido." },
      { name: "id", type: "string", default: '""', description: "id del párrafo." },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "tag",
    name: "Tag",
    layer: "Atom",
    packageExport: true,
    description: "Pill de categoría, opcionalmente removable o interactivo (teclado).",
    importLine: `import { Tag } from "${PACKAGE}";`,
    usage: `<Tag variant="cyan" removable onRemove={() => {}}>React</Tag>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Etiqueta." },
      {
        name: "variant",
        type: '"cyan" | "purple" | "gray" | "gradient"',
        default: '"cyan"',
        description: "Estilo.",
      },
      {
        name: "removable",
        type: "boolean",
        default: "false",
        description: "Botón cerrar con IconClose.",
      },
      { name: "onRemove", type: "() => void", default: "null", description: "Al pulsar cerrar." },
      {
        name: "interactive",
        type: "boolean",
        default: "false",
        description: "role=button y tabIndex para foco.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
];
