import { PACKAGE, type ComponentDocEntry } from "../types";

export const MOLECULE_LAYOUT_DOCS: ComponentDocEntry[] = [
  {
    id: "call-to-action",
    name: "CallToAction",
    layer: "Molecule",
    packageExport: true,
    description: "Enlace destacado tipo CTA con icono SVG opcional.",
    importLine: `import { CallToAction, IconArrowRight } from "${PACKAGE}";`,
    usage: `<CallToAction href="/signup" icon={<IconArrowRight />}>Empezar</CallToAction>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Texto del CTA." },
      { name: "href", type: "string", default: '"#"', description: "URL destino." },
      {
        name: "variant",
        type: '"primary" | "secondary" | "outline" | "ghost"',
        default: '"primary"',
        description: "Igual que Button.",
      },
      { name: "icon", type: "ReactNode", default: "null", description: "Icono a la izquierda." },
      { name: "target", type: "string", default: '"_self"', description: "Target del anchor." },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "card",
    name: "Card",
    layer: "Molecule",
    packageExport: true,
    description: "Contenedor con título, subtítulo y variantes de borde/hover.",
    importLine: `import { Card } from "${PACKAGE}";`,
    usage: `<Card title="Proyecto" variant="elevated">Contenido</Card>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Cuerpo de la card." },
      { name: "title", type: "string", default: "null", description: "Título opcional." },
      {
        name: "subtitle",
        type: "string",
        default: "null",
        description: "Subtítulo bajo el título.",
      },
      {
        name: "variant",
        type: '"default" | "elevated" | "gradient" | "minimal"',
        default: '"default"',
        description: "Estilo.",
      },
      {
        name: "hoverable",
        type: "boolean",
        default: "true",
        description: "Efectos hover en borde/sombra.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "code",
    name: "Code",
    layer: "Molecule",
    packageExport: true,
    description: "Bloque de código con Prism.js y botón copiar (iconos SVG).",
    importLine: `import { Code } from "${PACKAGE}";`,
    usage: '<Code codeContent="npm install pkg" language="bash" />',
    props: [
      { name: "codeContent", type: "string", default: "—", description: "Código a mostrar." },
      {
        name: "language",
        type: "string",
        default: '"javascript"',
        description: "Lenguaje Prism (javascript, bash…).",
      },
      {
        name: "compact",
        type: "boolean",
        default: "false",
        description: "Sin barra de lenguaje; botón copiar en la esquina (ideal para imports).",
      },
    ],
    notes: ["Incluye code-block.css en el bundle (tokens cyan/púrpura del kit)."],
  },
  {
    id: "container",
    name: "Container",
    layer: "Molecule",
    packageExport: true,
    description: "Contenedor centrado con max-width y padding responsivo.",
    importLine: `import { Container } from "${PACKAGE}";`,
    usage: `<Container size="lg" variant="section">{children}</Container>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Contenido." },
      {
        name: "size",
        type: '"sm" | "md" | "lg" | "xl" | "full"',
        default: '"md"',
        description: "Ancho máximo.",
      },
      {
        name: "variant",
        type: '"default" | "compact" | "relaxed" | "section"',
        default: '"default"',
        description: "Padding.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
  {
    id: "divided",
    name: "Divided",
    layer: "Molecule",
    packageExport: true,
    description: "Layout dos columnas: contenido principal + slot secundario.",
    importLine: `import { Divided } from "${PACKAGE}";`,
    usage: `<Divided secondaryContent={<Image ... />}>Texto</Divided>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Columna principal." },
      {
        name: "secondaryContent",
        type: "ReactNode",
        default: "—",
        description: "Columna lateral.",
      },
      {
        name: "hasBorder",
        type: "boolean",
        default: "false",
        description: "Borde exterior opcional.",
      },
    ],
  },
  {
    id: "grid",
    name: "Grid",
    layer: "Molecule",
    packageExport: true,
    description: "CSS grid con columnas fijas o breakpoints responsivos.",
    importLine: `import { Grid } from "${PACKAGE}";`,
    usage: `<Grid cols={3} gap="md" responsive={false}>{items}</Grid>`,
    props: [
      { name: "children", type: "ReactNode", default: "—", description: "Celdas." },
      {
        name: "cols",
        type: "number",
        default: "3",
        description: "Columnas si responsive=false (1,2,3,4,6).",
      },
      {
        name: "gap",
        type: '"sm" | "md" | "lg" | "xl"',
        default: '"md"',
        description: "Espacio entre celdas.",
      },
      {
        name: "responsive",
        type: "boolean",
        default: "true",
        description: "Grid adaptativo sm→lg.",
      },
      { name: "className", type: "string", default: '""', description: "Clases extra." },
    ],
  },
];
